stages:
  - version
  - build
  - publish
  - deploy

before_script: # Expose version variable in all jobs
  - source $CI_PROJECT_DIR/gitversion.properties && export GitVersion_NuGetVersion

gitversion:
  stage: version
  image:
    name: gittools/gitversion:5.0.0-linux-debian-9-netcoreapp2.2
    entrypoint: []
  before_script: [] # Prevent top-level before_script from running here
  script:
    - dotnet /app/GitVersion.dll /output buildserver
  artifacts:
    paths: [gitversion.properties]

dotnet:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - ./build.sh $GitVersion_NuGetVersion
  artifacts:
    paths:
      - src/ServiceBroker/obj/Docker/publish
    reports:
      junit: artifacts/test-results.xml

docker:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug # Only "debug" works because it contains a shell
    entrypoint: []
  script:
    - /kaniko/executor --cache=true
      --context dir://$CI_PROJECT_DIR/src/ServiceBroker
      --destination eu.gcr.io/axoom-image/myteam/myvendor-servicebroker:$GitVersion_NuGetVersion

.deploy:
  stage: deploy
  when: manual
  image: axoom/gcloud-helmfile
  environment:
    name: $CLUSTER_NAME
  variables:
    # Automatically creates database in Google Cloud SQL
    DATABASE_NAME: 
  script:
    - /entrypoint.sh

deploy:dev:
  extends: .deploy
  except: [master]
  variables:
    # gcloud
    GCP_PROJECT: axoom-platform-devstages
    CLUSTER_NAME: dev
    # helmfile
    ASPNETCORE_ENVIRONMENT: Development

deploy:dev:auto:
  extends: deploy:dev
  except: []
  only: [master]
  when: on_success

deploy:test:
  extends: .deploy
  variables:
    # gcloud
    GCP_PROJECT: axoom-platform-devstages
    CLUSTER_NAME: test
    # helmfile
    ASPNETCORE_ENVIRONMENT: Production

deploy:live:
  extends: .deploy
  variables:
    # gcloud
    GCP_PROJECT: axoom-platform-production
    CLUSTER_NAME: live
    # helmfile
    ASPNETCORE_ENVIRONMENT: Production
